### ISSUE TITLE
Idea: Supply List uses Typeahead.js

### ISSUE THREAD

**Issue by rgpass** [peacecorps/medlink#235]
Recipe:
* Log in on mobile
* Go to Place a Request
* Click Select Supply

Issue:
* Navigating a long list while on mobile can cause issues due to single scrolling event -- on desktops the scrolling is based off where your cursor is, however mobile doesn't have this

Proposed Solution:
* Use Typeahead.js (http://twitter.github.io/typeahead.js/examples/)
* Only issue will be if the person misspells it -- could add functionality to allot for misspellings

**Comment by jamesdabbs** [comment]
Added in 3dc08c9d3ddef4045730fd345b466986ca705e60 (though using chosen and not typeahead, but with that functionality).
