### ISSUE TITLE
Add function: flag requests

### ISSUE THREAD

**Issue by aroberts01** [peacecorps/medlink#330]
Add a flag of some sort, or check box similar to outlook, from the PCMO side.  The thought is that while they (the PCMO) OR more likely the medical secretary is processing requests there may be a request that they would like the PCMO to respond to directly, would like for another PCMO to take a look at, or would like to be reminded to review that volunteers history, before or after processing the request.  Not completely necessary but a function that may aid PCMO organization.
 Thanks James!

Mock-up 

![flag_pcm](https://cloud.githubusercontent.com/assets/7442963/2971932/ebd7809a-db6f-11e3-8d15-b4b2647ce9d8.png)

![flag_pcm_2](https://cloud.githubusercontent.com/assets/7442963/2971939/f8828ede-db6f-11e3-9547-08bfce29602a.png)

**Comment by jamesdabbs** [comment]
We have this functionality as of 3dc08c9d3ddef4045730fd345b466986ca705e60. Will continue to iterate on how we expose it (both in the UI and via text).
