### ISSUE TITLE
Testing Findings (Brain dump)

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#333]
Matthew 
- [ ] Line breaks don't show up in special instructions
- [ ] Is this susceptible to cross site scripting? 
- [ ] Select all icon or option at the top of the delivery, purchase, reimbursement columns
- [ ] Add the ability to edit/update an already responded to request
- [ ] Add numbers to pending requests to separate one order from another
- [ ] In an order when you scroll over a special instructions the gray highlight only goes into the top item. It should go over the whole thing. 

Andrea-
- [x] Rouge error when editing/adding a phone number
- [x] Bulk uploads does not trigger a welcome email
- [x] Bulk upload errors from Andrea
- [x] Reports- Item, Response and Instructions show up as code and not words in the reports. 
- [ ] Help hover text over special instructions
- [x] Pop up box with initial instructions (like a terms of service)
- [ ] No PII text below the special instructions

Patrick
- [ ] In place a request for a volunteer, as an admin the list is huge. Alphabetize the list to start, then limit by the country you are administrating. 
- [x] Expand timeframe for activation email

Possible Solutions to order response page
- [ ] Default delivery selected
- [ ] Move special instructions column to the right of the denial button
- [x] 1 min video with overview for both volunteers and staff

**Comment by jamesdabbs** [comment]
I _believe_ we've implemented all the parts of this that we intended to. If not, we'll open a new issue.
