### ISSUE TITLE
Hook up the SSL again

### ISSUE THREAD

**Issue by choquette33** [PeaceCorps/medlink#340]
I believe that we need to regenerate the SSL certificate and hook it back up. We hadn't been using it since the OpenSSL vulnerability was exposed. 

@jamesdabbs Let me know what I need to do...

**Comment by choquette33** [comment]
The SSL Certificate has expired and we would need a new one....

**Comment by jamesdabbs** [comment]
Just updated. I had to command-shift-R to see the fixed cert.

**Comment by choquette33** [comment]
Thanks @jamesdabbs!
