### ISSUE TITLE
Button Alignment Padding on Mobile

### ISSUE THREAD

**Issue by Mc4llister** [PeaceCorps/medlink#372]
When accessing the site from a mobile device, the sign in fields are missing left and right padding. The fields touch the far edges of the device screen in their current state.

![image](https://cloud.githubusercontent.com/assets/6920243/5075740/595011c4-6e63-11e4-8bc2-03b232f83a7f.png)

Credit: @thoracek

**Comment by choquette33** [comment]
#315 Also

**Comment by jamesdabbs** [comment]
This seems to have been incidentally resolved somewhere along the way.
