### ISSUE TITLE
Remove Inactive Menu Icon from Log-in Screen

### ISSUE THREAD

**Issue by Mc4llister** [PeaceCorps/medlink#375]
The menu icon on the main landing page before you sign in is not clickable to the user (which is good). We should hide it to avoid confusion and make it clear that menu contains actions that can only be used when you're logged in.

![image](https://cloud.githubusercontent.com/assets/6920243/5075940/0d43ce54-6e65-11e4-8625-3a5070b771af.png)

Credit: @thoracek

**Comment by wonmanlee** [comment]
Added pull request #397 for this issue.

**Comment by choquette33** [comment]
Completed.
