### ISSUE TITLE
Log In Fields Unrecognized by Mac KeyChain Manager

### ISSUE THREAD

**Issue by Mc4llister** [PeaceCorps/medlink#376]
The username and password fields on login are not being recognized as fields for Apple's Keychain Manager to auto-fill, per @thoracek.

Ideally these would be coded so that users who regularly logs in would have the benefit of these fields being auto-filled by their home computer.

**Comment by jamesdabbs** [comment]
Working for me on Safari and Chrome. Anybody else still having issues here?
