### ISSUE TITLE
Super Admin User Should be able to Edit Master Supply List

### ISSUE THREAD

**Issue by Mc4llister** [peacecorps/medlink#377]
There should be three levels of users as it pertains to their permissions when they interact with the medical supply list.

User - Is able to view and select items from the country-specific medical list
Country Administrator - Staff member that is able to remove items from the Master Supply list for their specific country.
Super Admin - Is able to remove, or add items to the Master Supply list, without restriction.

This is very important so that the tool doesn't require coding for updates to the master supply list.

Credit: @thoracek

**Comment by aroberts01** [comment]
I'm not entirely sure what the 4th layer means either.  I think it's important that PCMOs have the ability to edit the master list themselves in their individual countries as well as add a few (4?) country specific items. 

I found a spelling error in the supply list.  I'm sure it can be looked at when we implement the other parts.  I just didn't want to forget.  The spelling error was of Repellent.  The others are requests that i've had from a few countries.  we can discuss. 

![image](https://cloud.githubusercontent.com/assets/7442963/6108415/e10acda6-b040-11e4-9485-47c33fab36d0.png)

**Comment by choquette33** [comment]
Admin Level- ONLY - Still want to use this as a way to standardize this list of supplies

**Comment by jamesdabbs** [comment]
I believe this is _functionally_ resolved. A few dangling ends though (for @aroberts01, mostly):

* If you're still interested in the "other" option, could you open that as a new issue? I gather there's some push to standardize offerings, so I'd imagine there's a separate discussion to be had there.
* Admins can remove items from the supply list (like large gauze) directly. If there are any other changes you'd like made, can you send me an updated [supply.csv](https://github.com/peacecorps/medlink/blob/master/db/supply.csv)? There aren't any shortcode changes, right?
