### ISSUE TITLE
Add intro videos pop-ups for first time log-in

### ISSUE THREAD

**Issue by choquette33** [PeaceCorps/medlink#389]
[ ] For PCV Role- Create a pop up window that auto plays this youtube video upon first log in: https://www.youtube.com/watch?v=yTNr0Nh7WYU&list=PLlu3gBXpcBqpdISeH4SZ-9UpNKHLe8uXv

[ ] For PCMO and Admin Role- Create a pop up window that auto plays this youtube video upon first log in: https://www.youtube.com/watch?v=KkXb_5kkfwk

**Comment by mallorybucell** [comment]
@choquette33 - The simplest solution for implementing the welcome videos would require all current users to be directed to the appropriate video the first time they log in after the feature is deployed in production. Is that also something that needs to be addressed?

**Comment by choquette33** [comment]
That would be a good thing. I would love to trigger it for everyone!

**Comment by choquette33** [comment]
@mallorybucell Do you have an estimated timeline on this? We are planning some new country adds and would love to have the features you are working on implemented. Thanks!!!

**Comment by mallorybucell** [comment]
@choquette33 Apologies for the delay- I'm looking to finish this up this weekend and should be able to submit a pull request Monday if all goes to plan.
