### ISSUE TITLE
Custom SMS response for items not available in country

### ISSUE THREAD

**Issue by choquette33** [PeaceCorps/medlink#394]
If a user enters a correctly formatted supply short code, but that supply is not offered in the user's country the sms response should say: 

"Sorry, [item] is not currently offered by the med unit in your country. Resubmit your request in the format: Supply Short Code, Supply Short Code - Special Instructions."

This is a needed addition since our current set up responds with an error message stating that they have essentially entered the supply short code wrong. Which confuses users because they see that assume there is an error in the system.

**Comment by jamesdabbs** [comment]
This change is fine, but that message is > 160 characters. Do we need the "in the format: ..." bit, given that they submitted in the correct format already (just with bad supplies)?

**Comment by choquette33** [comment]
You're right. No need for the in the format bit.
