### ISSUE TITLE
Admins able schedule SMS reminders

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#400]
Add ability for admins to add a future date and time for sms messages being sent out through the bulk messaging feature (https://pcmedlink.org/admin/messages)

Note- 
The time should be the timezone of the country the volunteers belong to. 
There should be the ability to make a message reoccurring. 

Needs: Date, Message Content, Multiple Messages Scheduled
Wants: Time,

**Comment by jamesdabbs** [comment]
That last commit (3078c9e) implemented the bulk of this functionality.

@choquette33 - could you take a look at the new UI and let me know if that all makes sense / is missing anything? (Note: PCMOs do have access to the announcements for their country, and can create and send new ones on demand, but can't set up schedules.)

If you're happy with that, get me that list of timezones-per-country and I'll set up the scheduler to start running.

**Comment by choquette33** [comment]
@jamesdabbs - Loving all of this new functionality! I don't understand the UI on the announcements though. "Days" and "Hour" aren't intuitive to me.... I assume Days means date of the month? And hour means the time? But I don't understand the (-) negative aspect of it. 

I also don't see the simple- "send now" option. With this UI do they have to create an announcement and then go to that announcement and chose "send now"?

@aroberts01 - Have you made the time zone list yet? I thought I saw you starting that.

**Comment by jamesdabbs** [comment]
Yeah, negative is for "# days before the end of the month", which was one of the use cases you mentioned. Hour is which hour of the day to send the message on (in the local timezone) on each of those specified days.

The part I was unsure of with auto-sending-on-save was with how it interacts with scheduling stuff. Should we just assume that if you save a new announcement and it doesn't have a scheduled date attached (which would be true of every announcement that a PCMO creates), that it should be sent right away?

**Comment by choquette33** [comment]
So If I put "28", it would send on the 28th. If I put "-1" it would be one day before the last calendar date of the month? If we could use a picker or a drop down it would be more intuitive. Maybe a "{number-dropdown} days before the end of the month" 

What is negative for the time? We probably could use a drop down here and it would be easier as well.

**Comment by jamesdabbs** [comment]
Time wasn't intended to be negative; that's fixed now.

We can't use a picker, because if you pick the 20th, there's no way to tell if you mean the 20th or 10-or-however days before the end of the month.

We can't use a single dropdown because we have to support multiple dates per month. So if we're using dropdowns, we'd need provisions for adding and removing arbitrary numbers of "after the start of the month" selects and "before the end of the month" selects ... which seems awfully complex. Given that this is an admin-only feature - and that we have the schedule preview once you enter your initial dates - do we really need that? Or are you envisioning something simpler that I'm not?

**Comment by choquette33** [comment]
On the Time issue: Maybe a little tweak could be use the time format of 1:00, 12:00 type of format so you automatically understand it's a time of day. (ideally a 12 hour setup using am/pm)

For the date picker- I agree we can leave it as is for now since it is just an admin feature at this point, and we don't have a better solution. (And your implementation definitely makes more sense to me now)

I realize when I wrote this that I designated admins, (admins were the only ones who could message at the time) but I envision this being available  to the PCMO eventually as I would like to see the PCMO have as much control as possible.

**Comment by choquette33** [comment]
To answer the auto send question: On https://pcmedlink.org/announcements/new, how about a send now button in blue, and a Schedule for later option in gray. Then if the schedule for later option is selected the day and time fields are displayed. That would mean For PCMOs only the send now option would be visible.  

On https://pcmedlink.org/announcements/ - after I send an announcement, the button for send now goes gray which lets me know it's been sent. If I push the grayed out button again, nothing happens.  I think a good tweak would be for this button to display "resend to..." for any message previously sent. This allows me to repeat an announcement and removes a dead button.

**Comment by choquette33** [comment]
@jamesdabbs I believe that @aroberts01 sent you the time zones for each country in an email. Did you get those? I thought that what we were waiting on to activate the scheduler. Right?

**Comment by jamesdabbs** [comment]
She did. I've got the data loaded, but still need to wire them up to the announcement scheduler.

**Comment by choquette33** [comment]
Gotcha.

**Comment by jamesdabbs** [comment]
Working as of 3dc08c9d3ddef4045730fd345b466986ca705e60 (currently on staging, but we should be set once we roll that out to prod).
