### ISSUE TITLE
Inactivate accounts for those finishing their service

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#401]
We need a way to inactivate accounts for users who are no longer Peace Corps Employees or Volunteers. 

We would need a way to do this for individuals and in bulk. 

For individuals: 
a simple deactivate user option in the edit user UI (https://pcmedlink.org/admin/users/35/edit). A button next the the save user that would allow for inactivating the account. This should trigger an "You are about to inactivate "[user first and last name] Are you sure?" pop-up notification with the ability to confirm or cancel. 

For bulk: 
Admins should be able to upload a list of current users and have the option of archiving accounts not included in the spreadsheet. 

We could add a check box next to the "Overwrite existing users with duplicate entries" check box that  says "Inactivate users not in current bulk upload" 

Note: ONLY PCV ACCOUNTS, PCMO and admin should remain

![image](https://cloud.githubusercontent.com/assets/2973990/9067334/d544a8d0-3aaa-11e5-8222-c0344faaa28b.png)

Note: As of yesterday, We now have the ability to easily and accurately pull a current list from our Volunteer Database. We could set up a workflow within our office to upload current users on a monthly basis.

**Comment by jamesdabbs** [comment]
I believe this is complete. We'll take a swing at syncing to the uploaded CSV and inactivating accounts then in the next sprint.
