### ISSUE TITLE
Give Country Supplies Control To PCMO Accounts

### ISSUE THREAD

**Issue by choquette33** [PeaceCorps/medlink#408]
Allow for PCMO level accounts to edit their country's supply list. Admin level should still be able to edit for all as is currently implemented. 

Please add "Supplies" to the Gear Drop Down Menu for PCMO accounts which will lead them to this page for the country the PCMO is assigned to. 

https://pcmedlink.org/country_supplies

**Comment by jamesdabbs** [comment]
When you say "edit", does that still just mean "select from the master list"? Or does this allow wholesale edits?

**Comment by choquette33** [comment]
Select from master list
On Aug 4, 2015 6:44 PM, James Dabbs <notifications@github.com> wrote:When you say "edit", does that still just mean "select from the master list"? Or does this allow wholesale edits?

**Comment by jamesdabbs** [comment]
Rolled in to #423
