### ISSUE TITLE
Add "My Prescription Medication" to Supply List

### ISSUE THREAD

**Issue by choquette33** [PeaceCorps/medlink#409]
Add an supply entitled "My Prescription Medication" to this list of possible supply names. 

Use the short code: PREMD

**Comment by jamesdabbs** [comment]
Can do. Should it be available in all, none, or some countries by default?

**Comment by choquette33** [comment]
All be default
On Aug 5, 2015 12:22 AM, James Dabbs <notifications@github.com> wrote:Can do. Should it be available in all, none, or some countries by default?

**Comment by jamesdabbs** [comment]
Added. I would like to talk this over at some point, as it feels like a bandaid over a bigger problem, but I'm not sure how well we can actually address it without wrestling with HIPAA.

**Comment by choquette33** [comment]
Definitely a band-aid, but a band-aid that the users are demanding. Having explained the issues fully to them, they still want this.
