### ISSUE TITLE
Dead links?

### ISSUE THREAD

**Issue by jamesdabbs** [PeaceCorps/medlink#410]
The welcome videos and "learn more about the Peace Corps" link (on the confirmation page) seem to be broken (or at least down in development). Could you send those correct links?

**Comment by choquette33** [comment]
Welcome for PCMOs- https://www.youtube.com/watch?v=4L_XqUhXaMw
Welcome for PCVs- https://www.youtube.com/watch?v=qoZvHiSBTAs

Learn more about Peace Corps- http://www.peacecorps.gov/

**Comment by jamesdabbs** [comment]
Updated. Not sure how they got broken, but do be careful - if you upload a new video on Youtube in the future, I'll need the updated link.

The "Learn More" link is actually "Learn More About PC Medlink" ... is there a better url for that?

**Comment by choquette33** [comment]
We had it linked to a google form before. Moving forward let's use our promotional video: https://www.youtube.com/watch?v=uNkwizhzMVA
