### ISSUE TITLE
Improve performance on response tracker

### ISSUE THREAD

**Issue by jamesdabbs** [PeaceCorps/medlink#422]
Looks like it's making some costly queries (that Bullet isn't catching) that could definitely be improved.

@choquette33 - any chance you could give me access to the New Relic addon on Heroku? That would massively help spotting / debugging performance issues.

**Comment by choquette33** [comment]
@jamesdabbs- You mean Hawke?

**Comment by jamesdabbs** [comment]
No, I think the "Wayne" plan that's already enabled should be fine, but for some reason I just get a "not authorized" message when I try to look at it. I'm assuming that you need to go in to the "New Relic APM :: Newrelic" add-on and add me there, but that's just a guess.

**Comment by jamesdabbs** [comment]
There may have been a hiccup on the Heroku side. In any case, I've got access now. Will keep an eye on things. Thanks! :+1:
