### ISSUE TITLE
Supply management cleanup

### ISSUE THREAD

**Issue by jamesdabbs** [peacecorps/medlink#423]
A few issues here:

* [ ] Make sure that PCMOs can configure their offered supplies as a subset of the master Supply list (should be mostly working as of cad52e4520aed5d56163d380060f74bd8aba0359, but make sure that we have appropriate links to get there &c). #408
* [ ] Allow admin accounts to create and (soft) delete supplies from the master Supply list. #377
* [ ] Make sure we have tests! Part of the supply update is currently uncovered missed a production bug.
* [ ] Any other UI improvements / clean up that makes sense to do while we're in here.

**Comment by PTNielsen** [comment]
Pull Request created - https://github.com/PeaceCorps/medlink/pull/429

**Comment by jamesdabbs** [comment]
I think the last bits of this (unifying the display between the master supply list and the country supply lists) is completed in 3dc08c9d3ddef4045730fd345b466986ca705e60.
