### ISSUE TITLE
Flag for follow-up in "History Option" for a Vol leads to unauthorized page... even for admin

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#425]
When I clicked on the Flag for Follow up, in the https://pcmedlink.org/users/1/timeline page for an order by andrea roberts it kicked me to the https://pcmedlink.org/admin/users/new and told me I was not authorized to see the page, even though I was logged in as an admin.

**Comment by jamesdabbs** [comment]
This was quasi-deliberate: only a pcv can flag their own requests - https://github.com/PeaceCorps/medlink/blob/master/app/policies/response_policy.rb#L7.

The question is: should admins / PCMOs be able to flag them as well? Or should those buttons not be there if you're not able to flag them?

**Comment by choquette33** [comment]
I can see a use case for having PCMO level user being able to flag an item. Mainly, because an medical unit would likely have one person charged with the responsibility to follow up with volunteers who did not receive a package - the Medical Secretary. However, others in a med unit -like one of the PCMOs- could find out something didn't make it to a volunteer and would could benefit from being able to flag it, so that the med secretary could follow up. 

Therefore, I think a PCMO, and Admin should be able to mark things as flagged.
