### ISSUE TITLE
Redundant "Supply" title showing up redundantly

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#428]
"Supply" header showing up above each supply drop down. I expect the supply header to only show up once. 

![screenshot 2015-08-25 at 4 24 39 pm](https://cloud.githubusercontent.com/assets/2973990/9479727/88d70486-4b4c-11e5-8be6-5344ea4dd994.png)

**Comment by jamesdabbs** [comment]
Resolved in 3dc08c9d3ddef4045730fd345b466986ca705e60
