### ISSUE TITLE
.csv uploads not producing new users

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#431]
I am uploading a .csv of users for the DR

1. I choose the file and country
2. Click on the upload .csv button
3. The application starts working and eventually the chart of users that I just attempted to upload is displayed without errors on the page.
4. I do not receive confirmation of upload in the form of a pop up
5. When I check the users for the DR, none of the new users from the .csv are there.

**Comment by aroberts01** [comment]
@choquette33 @jamesdabbs 

Still receiving error for uploads.  "undefined method ' empty?' for nil:NilClass
Not sure what I'm doing wrong. it's in the same format as has always been.  I believe this is a new error message I'm receiving. 
![pcm_upl](https://cloud.githubusercontent.com/assets/7442963/10174421/b6240c32-66b7-11e5-9e4c-647946a8b3fe.JPG)

**Comment by jamesdabbs** [comment]
My guess would be that this is something about having blank rows at the end of the file and not handling them correctly. Could you email me a copy of the file you're trying to upload so I can take a look?

**Comment by aroberts01** [comment]
@jamesdabbs Hey, I was uploading Volunteers from Lesotho- and a new issue occurred.  I'm not having an 'issues' or 'errors' but the information isn't being loaded into the application.  You can see below- after I select the file and select to upload I am brought to this screen- with all the information being correct for all uploaded- but when you go to view users in Lesotho and I am not seeing Volunteers. 
![image001](https://cloud.githubusercontent.com/assets/7442963/10554708/13185dec-7434-11e5-9948-2a700ef592f8.jpg)

**Comment by aroberts01** [comment]
@jamesdabbs It's working now.  It helped to upload 4 volunteers with a small csv.  Then they all worked.

**Comment by jamesdabbs** [comment]
@aroberts01 - I'm not sure what the issue was, but glad it's working now. In the future, if you hit any unexpected upload errors, please send me a copy of the CSV you're uploading, so that I can troubleshoot it.
