### ISSUE TITLE
Add ability to delete announcements

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#433]
I realized that when I created a test announcement, that I never intended to send, I was not able to delete it. 

This created an undesirable UX because the "never" sent announcement remains at the top of the list of created announcements. This is a nuisance with just one, but would be a bigger problem as more "never" sent announcements are created. 

![screenshot 2015-09-29 at 10 04 13 am](https://cloud.githubusercontent.com/assets/2973990/10166399/d61621c2-6691-11e5-864a-b5736efbd1b7.png)

**Comment by jamesdabbs** [comment]
I went ahead and deleted the announcement directly, but this is a reasonable feature to add.

Earmarked this for @seanmpage, if he's interested.

**Comment by jamesdabbs** [comment]
Resolved in 3dc08c9d3ddef4045730fd345b466986ca705e60
