### ISSUE TITLE
Receipt Confirmation Pop-up on web

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#440]
_This function triggers a pop-up window asking PCV to confirm receipt of an outstanding order upon first log-in._

*Reasoning*- Right now we ask for confirmation of receipt through sms or through a semi-complicated web process. Responding via SMS costs money to the PCV and requires that they have enough credit on their phones to send an SMS to a US number. This can result in an annoying experience if multiple sms messages are sent and the PCV *can't* respond via sms. So ideally we would limit the amount of SMS asks we send to them and nudge them towards responding on the web if possible. 

*Logic*- 
This Pop-up alert appears upon login for  PCV's who have an outstanding order that has been responded to indicating approval for pick-up or delivery. Note- an pop-up should not appear for responses that have already been marked as received or flagged.

![img_20151023_135209](https://cloud.githubusercontent.com/assets/2973990/10700950/30828906-798f-11e5-9846-6e7fb1f6140f.jpg)

The content for the pop-up includes the text - Did you get your order of {supply 1, supply 2 and supply 3...} that was approved on {response date}? There should be two clean buttons one green with Yes and one Red with No. There should also be the ability to dismiss the message. 

The pop up should appear 14 calendar days after the response was sent to them. Same time of day as the time of the response.

If the PCV indicates Yes - The response is marked as received and archived.

If the PCV indicates No - The response is flagged but not archived.

If the PCV dismisses the pop-up - The pop-up should disappear but be triggered again on next log-in.

**Comment by jamesdabbs** [comment]
Resolved in 3dc08c9d3ddef4045730fd345b466986ca705e60
