### ISSUE TITLE
Editing a user leads to an error

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#443]
When editing a user, in this case myself, (https://pcmedlink.org/admin/users/105/edit) when I go to hit save after making changes it leads to an error. 

This is what shows up after hitting save on the user: https://pcmedlink.org/admin/users/105/

![screenshot 2015-11-02 at 2 28 01 pm](https://cloud.githubusercontent.com/assets/2973990/10891844/4c7cab96-816e-11e5-8621-6e72ae1bafc8.png)

**Comment by jamesdabbs** [comment]
Fixed in  abf3ae0
