### ISSUE TITLE
Display error when uploading incomplete .csv

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#445]
When loading a .csv that does not include a required column (for example: time_zone), there should be an error message that explains what went wrong.

Currently there is no error message so when you load a .csv without any other errors, it displays a clean table below but no indication of why the upload didn't happen.

**Comment by jamesdabbs** [comment]
Resolved in 3dc08c9d3ddef4045730fd345b466986ca705e60 (though I'm sure we'll take a few more iterations refining the UI here)
