### ISSUE TITLE
STAGING- Toggling supply kicks you to top of the page

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#455]
Little UX bug, but when I toggle a supply either as available or not available, the page defaults to bringing me back to the top. This is annoying when toggling items at the bottom of the list. We might just need to do a prevent default action on the javascript. 

![screenshot 2015-12-18 at 2 28 33 pm](https://cloud.githubusercontent.com/assets/2973990/11905368/258f7ad2-a594-11e5-8f0a-0e7ecb7c5589.png)

**Comment by jamesdabbs** [comment]
Unfortunately `preventDefault` only works if there's a _javascript_ event that's happening. For now, this is the best we can do.
