### ISSUE TITLE
Missing Order

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#459]
@jamesdabbs can you check in on this user? She is attempting to confirm receipt but there doesn't seem to be an outstanding order. 

https://www.pcmedlink.org/users/1068/timeline

**Comment by jamesdabbs** [comment]
This looks to be related to the responses that we manually removed from Nicaragua. This shouldn't happen with the new code, but I've added a Slack notifier in case it does so we don't keep spamming users like this.
