### ISSUE TITLE
Announcement Feature Not Functioning

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#471]
When sending out an announcement today, I noticed that the application wasn't actually sending anything out based on the message history, and the twilio logs. However, it is showing up as sent in the announcement page. 

![image](https://cloud.githubusercontent.com/assets/2973990/12681983/48db1274-c67f-11e5-9a86-778fbabb8369.png)

**Comment by jamesdabbs** [comment]
This is an ops issue, but should be resolved (and appropriately monitored) now.
