### ISSUE TITLE
Mobile favicons

### ISSUE THREAD

**Issue by jamesdabbs** [peacecorps/medlink#473]
I'm getting occasional errors in the logs from devices looking for apple favicons. We should generate a full set (using e.g. http://www.favicomatic.com).

@choquette33 - do we have a (hi-res) image to use for these?

**Comment by choquette33** [comment]
Ok- I went ahead and created this...

[favicomatic.zip](https://github.com/peacecorps/medlink/files/119910/favicomatic.zip)
