### ISSUE TITLE
"yes" answer to did you receive? not finding an outstanding order

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#474]
We may have already figured this out and fixed it, but I came upon this user and wanted to flag it. 

She responds yes to the received question, but there is no outstanding order for her.  

https://www.pcmedlink.org/users/1068/timeline

**Comment by jamesdabbs** [comment]
I _think_ this is resolved now. We certainly have better tools for configuring this, and have notifications that will alert us if it happens again, so I'm closing it for now.
