### ISSUE TITLE
Announcement bulk sms not sending out from twilio

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#475]
It looks like all of the bulk sms starting with the Zambia message on January 13th (https://www.pcmedlink.org/announcements) did not get sent out according to the twilio logs (https://www.twilio.com/user/account/messaging/logs). 

If we squish the bug here, we wouldn't want the sms messages to be sent out right now since they were time sensitive. Best case scenario, we could keep them as is and then resend them when the time is right.

**Comment by jamesdabbs** [comment]
Fixed in master.
