### ISSUE TITLE
Choose file on user upload leads to deadend

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#479]
When attempting to load a .csv of users, I choose a file, hit enter and then nothing happens. 

Checking the console log here is what I get: 

> XML Http Request cannot load https://s3.amazonaws.com/medlink-prod.jcd/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.pcmedlink.org' is therefore not allowed access. The response had HTTP status code 403.

**Comment by jamesdabbs** [comment]
CORS config on the production bucket didn't include the `www.` subdomain.
