### ISSUE TITLE
Bulk Upload for Zambia Leads to Error due to permission error (?)

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#480]
When attempting to do a bulk upload for Zambia on 3/18/2016 I ran into what looks like a permissions error. Everything worked until the very end when I went to hit save to confirm the new users and the inactivated users. After hitting save on that screen I got an error message: "The Change you wanted was rejected. Maybe you tried to change something you didn't have access to."

I was logged in as an Admin. The error created a rollbar notifier on the morning of 3/18.

**Comment by jamesdabbs** [comment]
Addressed in 5af5e21, but see #481 and #482 for better long-term fixes
