### ISSUE TITLE
Expose API Endpoint for Master Supply List

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#483]
@neerajrao discovered the need for this when the android app attempted to display an item not in the current country supply list for that user. (the user placed the order in a previous country)

**Comment by jamesdabbs** [comment]
@neerajrao - design question again here. Would you prefer to attach this to the existing `/supplies` endpoint (`available: true`), or to have a separate endpoint for the master supply list?

**Comment by neerajrao** [comment]
Have a separate endpoint would be my instinct. Or the client would have to filter out all `available:false` supplies every time an order is created.

**Comment by jamesdabbs** [comment]
@neerajrao - it's available on staging at `/api/v1/supplies/all`. Ping me if you need anything added to that.
