### ISSUE TITLE
Deleted Items from Master Supply list

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#484]
Related to #483 ...  @jamesdabbs  How do we handle displaying items in users' order history that include items that were deleted (or at least removed) from the master supply list? https://medlink-staging.herokuapp.com/supplies

Are the items actually deleted permanently? or do they go to an archive to be pulled from when needed? 
@neerajrao

**Comment by jamesdabbs** [comment]
Nothing gets deleted permanently. Items being removed from the supply list for a country just mean that you can't place new orders for those items in that country.

**Comment by neerajrao** [comment]
@jamesdabbs just to confirm, the website is using the master supply list when showing historical records, right? Because the user account that the app crashed on displays just fine in the website.

**Comment by jamesdabbs** [comment]
That's correct.

@choquette33 - Is there anything that needs to change here, or can we close this issue?
