### ISSUE TITLE
Scheduled announcement text displaying on non-scheduled annoucement

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#493]
I would expect the text below in the image to only display if the announcement is scheduled for repeat. However for a new announcement or one time announcement I wouldn't expect to see the text like this. 

In the image below I am logged in as a PCMO and creating an announcement for the first time: 

![screenshot 2016-05-17 at 3 05 16 pm](https://cloud.githubusercontent.com/assets/2973990/15335650/3c3a02e2-1c41-11e6-8b07-3a9023039d80.png)

I suggest we add something like this for this situation: Would you like to make this a reoccurring message? Please contact support to set your announcement schedule.

**Comment by jamesdabbs** [comment]
Hey @dankb82 - would you like to take a look at this one? I'd be happy to pair to get you setup / into the system.

**Comment by dankb82** [comment]
This looks great!  Thanks James. Let's talk next week. Have a good trip. 

Daniel Buompane

**Comment by choquette33** [comment]
Hi @dankb82 Thanks so much for helping out. Any luck moving this forward?
